function a = isVector( x , orient , minLength , maxLength )

    a = isnumeric( x ) ;
    
    if ( a )
        
        n = size( x ) ;
        
        a  =    ( length(n) == 2 )                     ...
             && (    (    isequal( orient , 'horz' )   ...
                       && ( n(1) == 1 )                ...
                       && ( n(2) >= minLength )        ...
                       && ( n(2) <= maxLength )        ...
                     )                                 ...
                  ||                                   ...
                     (    isequal( orient , 'vert' )   ...
                       && ( n(2) == 1 )                ...
                       && ( n(1) >= minLength )        ...
                       && ( n(1) <= maxLength )        ...
                     )                                 ...
                ) ;
         
    end

end