function isVectorHorzPositiveLong_Error( dataArray , nberEntries , ...
                                         strArray , strErrMsgID )
    if (    ( ~ isVectorHorzPositive( dataArray ) ) ...
         || ( nberEntries ~= length( dataArray ) ) )
        
        error( strErrMsgID , ...
               '%s must be a horizontal positive vector of length %d' , ...
               strArray , nberEntries ) ;
        
    end
    
end