function speciesInfo = SpeciesInfo( Symbol            , ...
                                    DescrShort        , ...
                                    DescrLong         , ...
                                    MolecularMass     , ...
                                    MolecularMassUnit )

    speciesInfo.Symbol            = Symbol            ;
    speciesInfo.DescrShort        = DescrShort        ;
    speciesInfo.DescrLong         = DescrLong         ;
    speciesInfo.MolecularMass     = MolecularMass     ;
    speciesInfo.MolecularMassUnit = MolecularMassUnit ;

end